name: Integration test

on:
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.4/stable
          provider: microk8s
          channel: 1.29-strict/stable
          lxd-channel: 5.20/stable
      - name: Run integration tests
        run: tox -e integration
      - name: Archive Tested Charm
        uses: actions/upload-artifact@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          name: tested-charm
          path: .tox/**/tls-certificates-requirer_ubuntu-22.04-amd64.charm
          retention-days: 5
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz
