name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-24.04
    steps:
      - uses: canonical/identity-credentials-workflows/.github/actions/prepare@v3.1.3
        with:
          workflows-ref: v3.1.3

      - uses: canonical/identity-credentials-workflows/.github/actions/setup-toolchains@v3.1.3
        with:
          toolchains: python

      - uses: canonical/identity-credentials-workflows/.github/actions/code-quality@v3.1.3
        with:
          python-enabled: "true"

      - uses: canonical/identity-credentials-workflows/.github/actions/unit-test@v3.1.3
        with:
          python-enabled: "true"

  build-for-integration:
    needs:
      - quality
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  build:
    needs:
      - quality
    uses: canonical/identity-credentials-workflows/.github/workflows/charm-build.yaml@v3.1.3
    with:
      path: ""
      arch: amd64

  build-arm:
    needs:
      - quality
    uses: canonical/identity-credentials-workflows/.github/workflows/charm-build.yaml@v3.1.3
    with:
      path: ""
      arch: arm64
      runner: '["self-hosted", "linux", "ARM64", "medium", "noble"]'

  integration-test:
    needs:
      - build-for-integration
    uses: ./.github/workflows/integration-test.yaml

  publish-charm-amd64:
    needs:
      - quality
      - integration-test
      - build
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: write
    uses: canonical/identity-credentials-workflows/.github/workflows/charm-publish.yaml@v3.1.3
    with:
      destination_channel: latest/edge
      artifacts-key: ${{ needs.build.outputs.artifacts-key }}
      charm-paths: ${{ needs.build.outputs.charm-paths }}
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  publish-charm-arm64:
    needs:
      - quality
      - integration-test
      - build-arm
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: write
    uses: canonical/identity-credentials-workflows/.github/workflows/charm-publish.yaml@v3.1.3
    with:
      destination_channel: latest/edge
      artifacts-key: ${{ needs.build-arm.outputs.artifacts-key }}
      charm-paths: ${{ needs.build-arm.outputs.charm-paths }}
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
