name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

jobs:
  lint-report:
    uses: canonical/identity-credentials-workflows/.github/workflows/lint-report.yaml@v1

  static-analysis:
    name: Static analysis
    uses: canonical/identity-credentials-workflows/.github/workflows/static-analysis.yaml@v1

  unit-tests-with-coverage:
    uses: canonical/identity-credentials-workflows/.github/workflows/unit-test.yaml@v1

  build-for-integration:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  build:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    uses: canonical/identity-credentials-workflows/.github/workflows/build-charm-amd.yaml@v1
    with:
      path: ""

  build-arm:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    uses: canonical/identity-credentials-workflows/.github/workflows/build-charm-arm.yaml@v1
    with:
      path: ""

  integration-test:
    needs:
      - build-for-integration
    uses: ./.github/workflows/integration-test.yaml

  publish-charm-amd64:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
      - build
    if: ${{ github.ref_name == 'main' }}
    uses: canonical/identity-credentials-workflows/.github/workflows/publish-charm.yaml@v1
    with:
      destination_channel: latest/edge
      artifacts-key: ${{ needs.build.outputs.artifacts-key }}
      charm-paths: ${{ needs.build.outputs.charm-paths }}
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  publish-charm-arm64:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
      - build-arm
    if: ${{ github.ref_name == 'main' }}
    uses: canonical/identity-credentials-workflows/.github/workflows/publish-charm.yaml@v1
    with:
      destination_channel: latest/edge
      artifacts-key: ${{ needs.build-arm.outputs.artifacts-key }}
      charm-paths: ${{ needs.build-arm.outputs.charm-paths }}
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
